### ISSUE TITLE
Tests don't catch the situation if instruction never completes

### ISSUE THREAD

**Issue by Maykeye** [RobertBaruch/n6800#1]
Found a bug, which might be nasty once cycle count for instruction will be around 9 that formal verification doesn't cover a case of single instruction that went into endless loop

To demonstrate: in mode_ext,

     with m.If(self.cycle == 1): 
            ....
            m.d.ph1 += self.cycle.eq(2)

replace  2 with 1 so whole branch looks like this

       with m.If(self.cycle == 1):
            m.d.ph1 += self.tmp16[8:].eq(self.Din)
            m.d.ph1 += self.pc.eq(self.pc + 1)
            m.d.ph1 += self.Addr.eq(self.pc + 1)
            m.d.ph1 += self.RW.eq(1)
            m.d.ph1 += self.cycle.eq(1) ### Introduced error
            if self.verification is not None:
                self.formalData.read(m, self.Addr, self.Din)

if you run simulation and look at traces, JMP 0xA010 will not be executed: PC will be increasing by 1 each cycle.
However running tests over `python3 core.py --insn jmp generate -t il core.il` will pass both cover and bmc.

This happens because we don't check if instruction was actually finished, only that it was started:
* we `cover` that  core.formalData.snapshot_taken, it was the at start of the instruction
* the meat of the verification, self.verification.check only gets called on the start of next instruction (cycle=0).

**Comment by XekriRedmane** [comment]
Indeed, you've discovered this flaw! And, I *just* discovered it in making the next video. I'll be fixing it, as soon as Windows stops locking my git file so I can upload. (soon to be tagged with 0.05.0 once the video goes out in a few hours).

**Comment by XekriRedmane** [comment]
Fixes are [here](https://github.com/RobertBaruch/n6800/blob/master/core.py#L412)
