### ISSUE TITLE
Wrong opcode for TAB and TBA instructions

### ISSUE THREAD

**Issue by lawrie** [RobertBaruch/n6800#3]
See https://github.com/RobertBaruch/n6800/blob/master/core.py#L372

The line should be:

```python
with m.Case("0001011-"):  # TAB, TBA
```

I found that while trying to implement a 6800 retro computer (the APF M1000, or Imagination Machine) on a Ulx3s board, see https://github.com/lawrie/ulx3s-nmigen-examples/tree/master/retro

**Comment by XekriRedmane** [comment]
Fixed, thanks!
